 // This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

// document.addEventListener('DOMContentLoaded', function() {
//   const filterButtons = document.querySelectorAll('[data-filter]');

//   filterButtons.forEach(function(button) {
//     button.addEventListener('click', function() {
//       const filter = button.dataset.filter;
//       const filterHeading = document.getElementById('filter-heading');
//       filterHeading.innerText = `All ${filter} Wollentier jobs in Berlin`;
//     });
//   });
// });

import DashboardController from "./dashboard_controller"
application.register("dashboard", DashboardController)
